const MatchingRace = [
    // レース出走情報　レース順
    [   // 第1レース
        [],
        [],
        {
            "grade": "G1",
            "raceTitle": "有馬記念",
            "raceDay": { "year": 24, "month": 9, "day": 23, "date": "月曜", },
            "startTime": "-:-",
            "season": "冬",
            "timeZone": "昼",
            "weather": "晴れ",
            "field": "芝",
            "condition": "良",
            "course": {"length": 25, "place": "中山", "rotate": "右・内", },
        },
    ],
    [   // 第2レース
        [],
        [],
        {
            "grade": "G1",
            "raceTitle": "チャンピオンズカップ",
            "raceDay": { "year": 24, "month": 9, "day": 23, "date": "月曜", },
            "startTime": "-:-",
            "season": "冬",
            "timeZone": "昼",
            "weather": "晴れ",
            "field": "ダ",
            "condition": "良",
            "course": {"length": 18, "place": "中京", "rotate": "左", },
        },
    ],
    [   // 第3レース
        [],
        [],
        {
            "grade": "G1",
            "raceTitle": "オークス",
            "raceDay": { "year": 24, "month": 9, "day": 23, "date": "月曜", },
            "startTime": "-:-",
            "season": "春",
            "timeZone": "昼",
            "weather": "晴れ",
            "field": "芝",
            "condition": "良",
            "course": {"length": 24, "place": "東京", "rotate": "左", },
        },
    ],
    [   // 第4レース
        [],
        [],
        {
            "grade": "G1",
            "raceTitle": "桜花賞",
            "raceDay": { "year": 24, "month": 9, "day": 23, "date": "月曜", },
            "startTime": "-:-",
            "season": "春",
            "timeZone": "昼",
            "weather": "晴れ",
            "field": "芝",
            "condition": "良",
            "course": {"length": 16, "place": "阪神", "rotate": "右・外", },
        },
    ],
    [   // 第5レース
        [],
        [],
        {
            "grade": "G1",
            "raceTitle": "スプリンターズステークス",
            "raceDay": { "year": 24, "month": 9, "day": 23, "date": "月曜", },
            "startTime": "-:-",
            "season": "秋",
            "timeZone": "昼",
            "weather": "晴れ",
            "field": "芝",
            "condition": "良",
            "course": {"length": 12, "place": "中山", "rotate": "右・外", },
        },
    ],
    [   // 第6レース
        [],
        [],
        {
            "grade": "G1",
            "raceTitle": "全日本ジュニア優駿",
            "raceDay": { "year": 24, "month": 9, "day": 23, "date": "月曜", },
            "startTime": "-:-",
            "season": "冬",
            "timeZone": "昼",
            "weather": "晴れ",
            "field": "ダ",
            "condition": "良",
            "course": {"length": 16, "place": "川崎", "rotate": "左", },
        },
    ],
]
